### ISSUE TITLE
Activities not showing up even after permissions are set

### ISSUE THREAD

**Issue by sunnycs121** [JMAConsulting/biz.jmaconsulting.activitytypeacl#8]
CMS - Drupal 7.69
CiviCRM - 5.13.6

Some new activities of type "Contact and Case" do not show up in create activity dropdown on civicrm contact page even though view, add, edit and delete actions are allowed to role of logged in user. 
After some debugging i noticed in file "activitytypeacl.php", in buildform hook "$activityOptions" variable do not have IDs of those new created activities. My assumption is "getPermissionedActivities" function is using this variable to determine if permissions for set for each activity ID found in said variable...?

**Comment by JoeMurray** [comment]
Hi Hassan, ciuld you verify if the user trying to view the activities has the required special permissions set up by this extension for the relevant Activity Types. Look in Drupal permissions for the user's roles.

**Comment by sunnycs121** [comment]
Hi @JoeMurray i have checked again, permissions are assigned to role correctly. Here is a screenshot of permissions being assigned to activity name "Grants: Compile Documentation" (activity type is enabled) which is not showing up in create activity dropdown also you will see another activity "Grants: Hassan Test" which is not given permissions is somehow showing up.

Screenshot of permissions: 
![image](https://user-images.githubusercontent.com/2493730/74172554-71213700-4bfe-11ea-9c11-41b6e603028c.png)

Screenshot of activity creation options:
![image](https://user-images.githubusercontent.com/2493730/74172630-92822300-4bfe-11ea-877f-593226491575.png)

![image](https://user-images.githubusercontent.com/2493730/74172686-aaf23d80-4bfe-11ea-81b7-0b9c58bb468b.png)

**Comment by sunnycs121** [comment]
Hi @JoeMurray I see you assigned task to @monishdeb Thanks very much. Is this something you are planning to actively work on and will be submitting a patch for? Any timeline is much appreciated. Thanks

**Comment by JoeMurray** [comment]
@monishdeb could you look at this before Tuesday?

**Comment by monishdeb** [comment]
Yes I will definitely take this issue on Monday. I will report here with a PR if any fix needed. Thanks!

**Comment by sunnycs121** [comment]
Hi @monishdeb any update on this?

**Comment by monishdeb** [comment]
Sorry @sunnycs121 its take me some time to fix this issue. Will let you know after submitting PR for it.

**Comment by sunnycs121** [comment]
@monishdeb sorry to be a pain but is there any update on this issue?

**Comment by monishdeb** [comment]
@sunnycs121 sorry for the delay. After investigation, I found that the issue is occuring because of the presence of ':' symbol in the Activity type. Let me explain further how this is affecting the permission check. 

This extension relies on ```CRM_ActivityTypeACL_BAO_ACL::getPermissionedActivities()``` function to exclude activity types on basis of permission, set for each activity type and action. Now the presence of colon ':' symbol in the permission text has a special meaning to CiviCRM core, as it is decoded [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Permission/Base.php#L46) where it splits the permission string into two parts on basis of colon ':'. In our case the permission string is __view activities of type Grants: Compile Documentation__ which is split into 'view activities of type Grants' and 'Compile Documentation'. The 1st part 'view activities of type Grants' doesn't make any sense as it doesn't falls under any Civiprefix for permission. Thus it simply rules out the permission from [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Permission/Base.php#L59). And eventually, return FALSE for these permission checks :
```
 delete activities of type Grants: Compile Documentation
add activities of type Grants: Compile Documentation
edit activities of type Grants: Compile Documentation
view activities of type Grants: Compile Documentation
view activities of type Grants: Hassan Test
edit activities of type Grants- Hassan Test
delete activities of type Grants: Hassan Test
add activities of type Grants: Hassan Test
```

Solution : I would suggest to change the custom Activity type name by removing the colon with other symbol or text. Say  ```Grants - Compile Documentation``` instead of ```Grants : Compile Documentation```

**Comment by sunnycs121** [comment]
@monishdeb Thanks for the update. I tried creating a new activity with name "Grants - Compile Documentation", this activity is available in dropdown list on activities tab of contact even if permissions are not set for the role. I have cleared drupal and civicrm cache before testing. Please see screenshots: 

![image](https://user-images.githubusercontent.com/2493730/75945523-7291f800-5e68-11ea-83f1-2e28176f519c.png)


![image](https://user-images.githubusercontent.com/2493730/75945474-568e5680-5e68-11ea-9c9d-1e89ecf6772d.png)

**Comment by Edzelopez** [comment]
Hi @sunnycs121 

Could you please confirm you renamed the activity type name as well as the label? The test that CiviCRM uses depends on the name of the activity, which does not change when the label is updated from the browser. I would urge you to either use the API explorer to update the activity name, or update it from the database. If you would like instructions to do either, please let me know.

**Comment by sunnycs121** [comment]
We updated activity names, now its working as expected.

Thanks
